{% set name = "vorbis" %}
{% set version = "1.3.6" %}
{% set sha256 = "6ed40e0241089a42c48604dc00e362beee00036af2d8b3f46338031c9e0351cb" %}

package:
  name: lib{{ name|lower }}
  version: {{ version }}

source:
  fn:  lib{{ name }}-{{ version }}.tar.gz
  url: http://downloads.xiph.org/releases/{{ name }}/lib{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  run_exports:
    # https://abi-laboratory.pro/index.php?view=timeline&l=libvorbis
    - {{ pin_subpackage('libvorbis') }}

requirements:
  build:
    - cmake  # [win]
    - {{ compiler('c') }}
    - make  # [unix]
  host:
    - libogg
  run:
    - {{ pin_compatible('libogg') }}

test:
  requires:
    - python {{ environ['PY_VER'] + '*' }}  # [win]
  commands:
    - test -f $PREFIX/lib/libvorbis.dylib  # [osx]
    - test -f $PREFIX/lib/libvorbisenc.dylib  # [osx]
    - test -f $PREFIX/lib/libvorbisfile.dylib  # [osx]
    - test -f $PREFIX/lib/libvorbis.so  # [linux]
    - test -f $PREFIX/lib/libvorbisenc.so  # [linux]
    - test -f $PREFIX/lib/libvorbisfile.so  # [linux]
    - if not exist %LIBRARY_LIB%\\libvorbis.lib exit 1  # [win]
    - if not exist %LIBRARY_BIN%\\libvorbis.dll exit 1  # [win]

about:
  home: https://www.xiph.org/
  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYING
  summary: "Vorbis audio format"
  description: Lossy audio codec with a fixed point decoder.
  doc_url: https://wiki.xiph.org/

extra:
  recipe-maintainers:
    - dschreij
